plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.16.0"

minimal_mistakes_skin: "contrast" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise

title: "ONION 2020"

include: 
  - _pages
  - _data
  - assets

author:
  name      : "IntelLang 2020"
  avatar    : "/assets/robot.jpg"
  bio       : " Intelligent Information Processing and Natural Language Generation"
  location  : "Santiago de Compostela, Spain"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true