plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.16.0"

minimal_mistakes_skin: "contrast" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise

title: "ONION 2020"

include: 
  - _pages
  - _data
  - assets

author:
  name      : "ONION 2020"
  avatar    : "/assets/onion.svg"
  bio       : "Workshop on peOple in laNguage, vIsiOn and the miNd. This workshop is dedicated to multimodal approaches to describing people in terms of their bodies and faces."
  location  : "Marseille, France"

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true